name: CNU WITH Bot (Selenium)

on:
  # push: #(ì¦ì€ action ë°©ì§€)
  #schedule:
    # í•œêµ­ ì‹œê°„: 09, 12, 15, 18, 21ì‹œ ì‹¤í–‰
   # - cron: '15 0,3,6,9,12 * * *'
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ ë²„íŠ¼ í™œì„±í™”

permissions:
  contents: write # ë´‡ì´ json íŒŒì¼ì„ ìˆ˜ì •í•´ì„œ ì˜¬ë¦´ ìˆ˜ ìˆëŠ” ê¶Œí•œ

jobs:
  run-with-bot:
    runs-on: ubuntu-latest
    
    # ì‹œê°„ëŒ€ ì„¤ì •
    env:
      TZ: 'Asia/Seoul'

    steps:
      - name: ì €ì¥ì†Œ ì½”ë“œ ê°€ì ¸ì˜¤ê¸°
        uses: actions/checkout@v4

      - name: íŒŒì´ì¬ ì„¤ì •í•˜ê¸°
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: í¬ë¡¬ ë¸Œë¼ìš°ì € ì„¤ì¹˜
        uses: browser-actions/setup-chrome@latest

      - name: ë¼ì´ë¸ŒëŸ¬ë¦¬ ì„¤ì¹˜í•˜ê¸°
        run: |
          pip install requests beautifulsoup4 selenium webdriver-manager python-dotenv

      - name: WITH ë´‡ ì‹¤í–‰í•˜ê¸°
        env:
          CNU_ID: ${{ secrets.CNU_ID }}
          CNU_PW: ${{ secrets.CNU_PW }}
          
          # í•™ìƒ ê³µì§€ìš© ì›¹í›„í¬
          with_WEBHOOK_URL: ${{ secrets.with_WEBHOOK_URL }}
          
          # ê´€ë¦¬ì ì—ëŸ¬ ì•Œë¦¼ìš© ì›¹í›„í¬
          MONITOR_WEBHOOK_URL: ${{ secrets.MONITOR_WEBHOOK_URL }}
        run: |
          python src/with_bot.py

      - name: ë§ˆì§€ë§‰ ì½ì€ ê¸€ ì €ì¥í•˜ê¸° (Auto Commit)
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          
          # data í´ë” ì•ˆì˜ with ë°ì´í„° íŒŒì¼ ë‹´ê¸°
          git add -f data/with_data.json || true
          
          # 2. ë³€ê²½ì‚¬í•­ í™•ì¸ ë° ì €ì¥
          if git diff --staged --quiet; then
            echo "ğŸ’¤ ë³€ê²½ëœ ë‚´ìš©ì´ ì—†ìŠµë‹ˆë‹¤."
          else
            echo "ğŸ’¾ ìƒˆë¡œìš´ ê¸€ì„ ë°œê²¬í•˜ì—¬ ê¸°ë¡ì„ ì—…ë°ì´íŠ¸í•©ë‹ˆë‹¤."
            git commit -m "Bot: WITH ë´‡ ë°ì´í„° ê°±ì‹ "
            git pull --rebase origin main
            git push
          fi
